name: Build and Package Chrome Extension

on:
  push:
    branches: [ main, release/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (none required)
        run: echo "No build deps"

      - name: Validate manifest
        run: |
          test -f manifest.json
          cat manifest.json | jq '.' > /dev/null

      - name: Prepare package folder
        run: |
          mkdir dist
          rsync -av --exclude='.git' --exclude='dist' --exclude='.github' ./ dist/

      - name: Create ZIP
        run: |
          cd dist && zip -r ../focus-timer-pro.zip . && cd -

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: focus-timer-pro
          path: focus-timer-pro.zip
