name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZIP
        run: |
          mkdir dist
          rsync -av --exclude='.git' --exclude='dist' --exclude='.github' ./ dist/
          cd dist && zip -r ../focus-timer-pro.zip . && cd -
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: focus-timer-pro.zip
